# Generated by Django 5.1.3 on 2024-11-05 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('kitchenname', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='kichenphotos/')),
                ('coverImage', models.ImageField(upload_to='kitchenphotos/')),
                ('documents', models.FileField(upload_to='chefdocs/')),
                ('exprience', models.IntegerField()),
                ('ph', models.IntegerField()),
                ('speciality', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kichenprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
