# Generated by Django 5.1.3 on 2024-11-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenprofile',
            name='image',
            field=models.ImageField(upload_to='kitchenphotos/'),
        ),
    ]
