# Generated by Django 5.1.2 on 2024-10-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='frequently_bought_with',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='frequently_bought_with',
            field=models.TextField(null=True),
        ),
    ]
